### ISSUE TITLE
Updated big.in

### ISSUE THREAD

**Issue by asterismo** [smirik/mercury#17]
Hi, i notice the big.in has an epoch of 2457724.5D0 and th ifile is 3 years old. I wonder if this is extracted by the DE431 positions. JPL/Horizons has planet positions for DE431 and the epoch in that paper is JD (TDB) 2440400.5, are big.in positions bettert than these?

**Comment by idovgalyov-4xxi** [comment]
Hi, @asterismo!
Sorry for a great response delay, I still don't get notifications from this repo.
The planetary data in `-.in.sample` files were provided by package authors, they are suitable for simulations with large periods of integration. However, You always can use other values for Your own purposes.

Also, You may take a look at the discussion below (it turned out that using JPL data might lead to chaotic behavior of Pluto's motion within 1Myr simulation period):
https://github.com/4xxi/mercury/issues/15
