### ISSUE TITLE
mfo_user user define force Issue

### ISSUE THREAD

**Issue by tyy-cc** [smirik/mercury#23]
Hi,

I have a problem when I write user define force in mfo_user function. I have attached the zip file below. This problem still exists if change the code to Fortran 90.

In mercury6_2_default_newJ2_constK2.for, I define the force in mfo_user functions.
When `J2planet = xco/((time/day) + 1.d6)` (line:268), all looks good. 

However,  if I have
`rtime = (time/day) + 1.d6`
`J2planet = xco/rtime`

It will cause planets being ejected at the beginning, and *.aei files have only one timestep data.
info.out will have:
` K342e                     ejected at            8.22000 days `
`K342b                     ejected at            8.22000 days `
` K342c                     ejected at            8.22000 days `
 `K342d                     ejected at           16.44000 days `

This issue really confuses me because the assignments look all right. And there are many **similar** circumstances will cause ejection at the beginning (I only show one example here to clarify...), which looks pretty unreasonable.

Do you have any idea about this situation?
Thank you so much for the help in advance!

**Comment by idovgalyov-4xxi** [comment]
Hi, @tyy-cc !
I picked the code from your archive and launched in my environment (with default .in-files substituted by yours). I use Ubuntu 19.10 with `gcc` version 9.2.1 (`gfortran` version is the same).
I also modified your subroutine to print some debug information.
I compiled and ran two versions of your code (one for your original expression and one for `rtime` injection).

Version 1:
```
        J2planet = xco/((time/day) + 1.d6)
        if ((time .le. 8.23d0) .and. (time .ge. 8d0)) then
            write(*, *) '1: ', xco, time, day
            write(*, *) '2: ', time/day, (time/day) + 1.d6
            write(*, *) '3: ', xco/((time/day) + 1.d6), J2planet
            write(*, *) '--------------------'
        end if
```

Version 2:
```
        real*8 J2planet_orig

        ...

c        J2planet = xco/((time/day) + 1.d6)
        J2planet_orig = xco/((time/day) + 1.d6)
        rtime = (time/day) + 1.d6
        J2planet = xco/rtime
        if ((time.le. 8.23d0) .and. (time.ge. 8d0)) then
            write(*, *) '1: ', xco, time, day
            write(*, *) '2: ', time/day, (time/day) + 1.d6
            write(*, *) '3: ', xco/((time/day) + 1.d6), J2planet_orig
            write(*, *) '4: ', rtime, xco/rtime, J2planet
            write(*, *) '--------------------'
        end if
```

Also, I ran additional version based on version 2 without printing debug information to avoid possible side effects.

All three results look pretty similar and none of them doesn't have any ejections.
I have attached log files containing console output for each version so you can compare them with each other (see "log", "log2", "log3").
[mercury_console_output.zip](https://github.com/4xxi/mercury/files/4512205/mercury_console_output.zip)

As far as I can't reproduce your issue, I have few ideas of what goes wrong so I can recommend the following:

1. I noticed some indentations in your code included tab symbols mixed with spaces. Maybe that's not the issue, but I would recommend you to use only spaces (in some editors, tabs may look as wide as several spaces that can break f77 code format and cause errors).
2. It may depend on compiler version or operation system, sometimes compiler may treat float constants as single-precision floats unless written with "d" exponent. All in all I recommend to avoid typing float literals without "d" exponent. In your example, using "d0" at the end of expression `xco = 46.84138` resulted in slightly different output numbers (compare "log" and "log_d0" in attachment, however, the main result remains the same).

(I have no doubts that you modified your Makefile to compile your version of `mercury6_2.for` instead of default source file.)

If the issue still exists on your side, you may need to provide more information for your example, e.g. temporary and result files produced while running, compiler version, debug prints, etc.

**Comment by henry2004y** [comment]
Hi Ilya,

@tyy-cc sent me this code two days ago. I'm interested in debugging this because this is like a magic bug for me.

From the file tyy-cc posted, I simply added two lines to the`mfo_user` subroutine:
```fortran77
      subroutine mfo_user (time,jcen,nbod,nbig,m,x,v,a)
c
      implicit none
      include 'mercury.inc'
c
c Input/Output
      integer nbod, nbig
      real*8 time,jcen(3),m(nbod),x(3,nbod),v(3,nbod),a(3,nbod)
c
c Local
      integer j
c-------------------J2-----------------------------------------------------------
	     real*8 J2planet,planetm,Rplanet
       real*8 prx,pry,prz,pr2,fac,pax,pay,paz
	     real*8 aJ2(3,nbod),aPN1(3,nbod),rd(3)
       real*8 vm2(3),vr(3),vrv(3,nbod)
	     real*8 cons(3),kk,c,b,btime
c----------k2-----------------------------
       real*8 inK2,rtime
       real*8 day,xco
       logical haha_bug
c dim is the number of datapoints in time-k2 file
       parameter (day = 365.25d0)
c       parameter (b = 3.5025d2)
       parameter (btime = 1.d6)
       parameter (xco = 46.84138)
c       parameter (inK2 = 0.133737)

        haha_bug = .true.
  	     J2planet = xco/((time/day) + 1.d6)
c       write(*,*) 'rtime1:',rtime
c       J2planet=0.001;
	     planetm=1.13
	     Rplanet=1.47*0.00465
c       write(*,*) 'J2_1:',tem

	     do j = 2, nbod
c           write(*,*) 'J2_2:',tem
		       prx=x(1, j)
		       pry=x(2, j)
		       prz=x(3, j)
	    	   pr2=x(1, j)*x(1, j)+x(2, j)*x(2, j)+x(3, j)*x(3, j)
c		write(*,*) 'pr2:', pr2
		      fac = 3.*K2*J2planet*planetm*Rplanet*Rplanet/2./(pr2**3.5)
		       pax  = -fac*prx*(prx*prx + pry*pry - 4.*prz*prz)
		       pay  = -fac*pry*(prx*prx + pry*pry - 4.*prz*prz)
		       paz  = -fac*prz*(3.*(prx*prx + pry*pry) - 2.*prz*prz)
       		 aJ2(1,j) = pax
       		 aJ2(2,j) = pay
        	 aJ2(3,j) = paz
      end do

c PN1:
	     c = 173.1445988
        do j = 2, nbod
            rd(j) = sqrt(x(1,j)*x(1,j)+x(2,j)*x(2,j)+x(3,j)*x(3,j))
            vm2(j) = v(1,j)*v(1,j) + v(2,j)*v(2,j) + v(3,j)*v(3,j)
            vr(j) = v(1,j)*x(1,j) + v(2,j)*x(2,j) + v(3,j)*x(3,j)
c            write(*,*) 'J2_3:',tem
        end do

        do j = 2, nbod
            vrv(1, j) = 4. * vr(j) * v(1,j)
            vrv(2, j) = 4. * vr(j) * v(2,j)
            vrv(3, j) = 4. * vr(j) * v(3,j)
            cons(j) = (4. * m(1) / rd(j)) - vm2(j)

c            write(*,*) 'J2_4:',tem
        end do

        do j = 2, nbod
            kk = m(1) / ( rd(j)**3. * c**2. )
            aPN1(1,j) = kk * ( cons(j) * x(1,j) + vrv(1,j) )
            aPN1(2,j) = kk * ( cons(j) * x(2,j) + vrv(2,j) )
            aPN1(3,j) = kk * ( cons(j) * x(3,j) + vrv(3,j) )
c            write(*,*) 'pa1=',aPN1(1,j),'pa2=',aPN1(2,j)
c             write(*,*) 'J2_5:',tem
        end do


        do j = 2, nbod
            a(1,j) = aJ2(1,j)+aPN1(1,j)
            a(2,j) = aJ2(2,j)+aPN1(2,j)
            a(3,j) = aJ2(3,j)+aPN1(3,j)
c          write(*,*) 'J2_6:',tem
c            write(*,*) 'a1=',a(1,j),'a2=',a(2,j),'a3=',a(3,j)
        end do
c
c---------Default---------------------------------------------------------------------
c
c      do j = 1, nbod
c       a(1,j) = 0.d0
c        a(2,j) = 0.d0
c        a(3,j) = 0.d0
c      end do
c      write(*,*) time,'261'
c
c----------Default--------------------------------------------------------------------
c
      return
      end
```

I compiled the code on my Mac with gfortran9:
```
gfortran -o m6 mercury6_2_default_newJ2_constK2.for
```

and modified the stopping time in `param.in` to `stop time (days) =3.6525d1`.

Then if you run the code,
```
./m6
```
in the `info.out` file, you will see
```
 K342e                     ejected at            8.22000 days 
 K342b                     ejected at            8.22000 days 
 K342c                     ejected at            8.22000 days 
 K342d                     ejected at           16.44000 days 
```
which is not there without the two added lines. Amazing~

**Comment by idovgalyov-4xxi** [comment]
Hello, @henry2004y !
I ran your version (with two lines added) and reproduced this magic bug.
Indeed, It looks very strange.
And it looks even more strange because when I try to print `J2planet` value after its calculation, all becomes normal. So I even cannot be sure whether this weird behavior is caused by exactly that expression or not.
By now I have some ideas how to get around this problem (not solve it), see my next comment.

**Comment by idovgalyov-4xxi** [comment]
@tyy-cc ,
I could see from the last example provided by @henry2004y that the way you used to compile the program looked like
```
gfortran -o mercury6 mercury6_2_default_newJ2_constK2.for
```
You may try to add an optimization key -O2 (O is letter, not digit) like this:
```
gfortran -O2 -o mercury6 mercury6_2_default_newJ2_constK2.for
```
It tells to compiler to perform some optimization tricks on compilation time that can slightly increase runtime speed. Also, it somehow makes this bug disappear.
I use this key by default, that's why I couldn't find the bug in the first example.

You can also use Makefile included in repo to automatically build or clean your workspace with all needed keys included (enables optimizations and hides possible unnecessary warnings). Just type `make` in prompt to see the list of possible commands.

**Comment by henry2004y** [comment]
> @tyy-cc ,
> I could see from the last example provided by @henry2004y that the way you used to compile the program looked like
> 
> ```
> gfortran -o mercury6 mercury6_2_default_newJ2_constK2.for
> ```
> 
> You may try to add an optimization key -O2 (O is letter, not digit) like this:
> 
> ```
> gfortran -O2 -o mercury6 mercury6_2_default_newJ2_constK2.for
> ```
> 
> It tells to compiler to perform some optimization tricks on compilation time that can slightly increase runtime speed. Also, it somehow makes this bug disappear on my side.
> I use this key by default, that's why I couldn't find the bug in the first example.
> 
> You can also use Makefile included in repo to automatically build or clean your workspace with all needed keys included (enables optimizations and hides possible unnecessary warnings). Just type `make` in prompt to see the list of possible commands.
> 
> I would recommend to keep this issue opened as there is still no "fair" solution for this bug.

With optimization level O2, gfortran is smart enough to remove unused local variables as if it doesn't appear in the code.

I really want to see the root cause of this issue. Here are several things I observed during the tests:
1 Whatever the type or name of the local variable, once you initialize it, it causes problem.
2 What happens in the user subroutine matters. if you remove some of the loops in the subroutine, the problem disappears
3 I used an auto-conversion script to translate the source code to Fortran 90, but the problem sustained.
